publisher_list:
#  - name: WaveDetectionPublisher
#    scope: /ros4rsb/handPos
#    topic: $$$ignored$$$
  - name: LaserDataPublisher
    scope: /ros4rsb/laserscan
    topic: /scan
  - name: OdometryDataPublisher
    scope: /ros4rsb/odometryData
    topic: /odom
#  - name: SpeedDataPublisher
#    scope: /ros4rsb/speedData
#    topic: /odom
#  - name: StallDataPublisher
#    scope: /ros4rsb/stallData
#    topic: /diagnostics
  - name: SlamMapPublisher
    scope: /ros4rsb/slamMap
    topic: /map
  - name: SlamPosPublisher
    scope: /ros4rsb/slampose/meka
    topic: /meka_roscontrol_base_controller/odom
  - name: GlobalPlanPublisher
    scope: /ros4rsb/globalplan
    topic: /move_base/NavfnROS/plan
  - name: PersonDataPublisher
    scope: /hri/persons
    topic: /people_tracker/people
listener_list:
  - name: BoxListener
    scope: /boxes
    topic: box_marker
#  - name: CollisionBoxListener
#    scope: /clafu/results/region3d
#    topic: $$$ignored$$$
  - name: CollisionSurfaceListener
    scope: /clafu/table
    topic: $$$ignored$$$
server_list:
  - name: NavigationServer
    scope: /nav_server
    topic: $$$ignored$$$
  - name: ControllerServer
    scope: /ros4rsb/ros_control # rsp scope
    topic: $$$ignored$$$ #
